### ISSUE TITLE
Query Engine V0

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/query-engine#1]
## Rationale / Use Cases

The Query Engine is a component that connects dApps with The Graph by managing how queries are being processed against index nodes in the hybrid network, including index node discovery, payments, query splitting/routing and verification.

The Query Engine described here uses GraphQL as the dApp query language and is considered the reference implementation. Developers can either embed it in their dApps using frameworks such as [Apollo ](https://www.apollographql.com/) or use a standalone [Query Node ](https://github.com/graphprotocol/query-engine/issues/2) that is based on it.

_Query Engine V0_ stands for the first version of the query engine that is fully compatible with the hosted service and lacks features such as payments.

### Primary Requirements

* Uses GraphQL
* Runs on the server and in the browser
* Discovers index nodes registered with The Graph
  * Resolves subgraph names using the GNS
  * Identifies indexer addresses and index node URLs using Stacking and Service Registry contracts
* Distributes queries across index nodes based on prices and performance parameters
* Integrates well with existing GraphQL ecosystem — e.g. Apollo

### Secondary Requirements

* All parts of the query engine — node discovery, query planning, payment channels etc. — can be swapped out to allow for easy testing and experimentation
* The query engine is easy to debug — e.g. with browser devtools

### API Requirements

* The GraphQL API is fully compatible with the hosted service

## Proposed User Experience

The Query Engine V0 comes in the shape of two packages:

* `@graphprotocol/query-engine` includes the query engine itself, as well as interfaces and default implementations for all related components (node discovery, query planning, query execution etc.).

* `@graphprotocol/query-engine-apollo` includes a batched Apollo link that forwards GraphQL requests to an instance of the Query Engine. This allows for seamless integration into dApps that use Apollo.

The Query Engine V0 (versions `0.x.x`) is fully compatible with the hosted service. This means it assumes index nodes provide the same GraphQL API as the hosted service.

It includes:

* Subgraph name resolution
* Node discovery
* Price discovery
* Query planning and execution using the current GraphQL API

It does not include:

* Read interface support
* Wire protocol support
* Payments

### `@graphprotocol/query-engine`

A TypeScript library to instantiate a Query Engine with a subgraph name or ID. It takes GraphQL requests with one or more operations and returns GraphQL responses. In combination with `@graphprotocol/query-engine-apollo`, it can be plugged into Apollo clients and servers easily.

#### Types an interfaces

```typescript
/**
 * Fundamental types
 */

type Address = string
type SubgraphId = string
type SubgraphName = string
type SubgraphNameOrId = SubgraphName | SubgraphId

interface Indexer {
  signer: Address
  subgraph: Set<SubgraphId>
}

interface IndexNode {
  signer: Address
  url: URL
  subgraphs: Set<SubgraphId>
}

interface IndexNodePriceData {
  /* ... */
}

interface IndexNodeWithPrices {
  signer: Address
  url: URL
  subgraphs: Set<SubgraphId>
  prices: IndexNodePriceData
}

/**
 * Node discovery
 */

// Resolves subgraph names/IDs to subgraph IDs
type SubgraphNameResolver = async (names: SubgraphNameOrId[]) => Promise<SubgraphId[]>

// Maps from subgraph IDs to approved signer addresses for each subgraph
type SubgraphIndexersResolver = async (subgraphs?: SubgraphId[]) => Promise<Indexer[]>

// Maps from signer address and subgraph IDs to index node
type IndexNodeURLResolver = async (signers: Indexer[]) => Promise<IndexNode[]>

// High-level index node resolver; combines all of the above
type IndexNodeResolver = async (subgraphs?: SubgraphNameOrId[]) => Promise<IndexNode[]>

/**
 * Price discovery
 */

type PriceFetcher = async (nodes: IndexNode[]) => Promise<IndexNodeWithPrices[]>

/**
 * Query planning!
 */

// A GraphQL query
interface Query {
  document: graphql.Document
  variables: Record<string, any>
  operationName: string
}

// A GraphQL query result
type QueryResult = graphql.ExecutionResult<{ [key: string]: any }>

// A query plan for a GraphQL query; essentially parallel and nested
// subqueries, each of which is annotated with a prioritized list of
// index nodes to try to send them to
interface QueryPlan {
  /* ... */
}

// Initial GraphQL-based query planner; this is a stop-gap solution until
// we have a fully specified query language for the read interface
type QueryPlanner = async (
  query: Query,
  nodes: IndexNodesWithPrices[],
) => Promise<QueryPlan>

/**
 * Query execution
 */

// Initial GraphQL-based query executor; this is a stop-gap solution until
// we have a fully specified query language for the read interface
type QueryExecutor = async (plan: QueryPlan) => Promise<QueryResult>

/**
 * Query engine
 */

type QueryEngine = async (query: Query) => Promise<QueryResult>
```

### Default implementations

The package exports the query engine as well as default implementations for the different components such that they can be used as follows:

```typescript
import { createQueryEngine } from '@graphprotocol/query-engine'

// Using a specific subgraph and default components
let engine = createQueryEngine({
  subgraph: "Qm...",
})

// Using a custom subgraph name resolver
let engine = createQueryEngine({
  subgraph: "jannis/test",
  nameResolver: async (names: string[]) => {
    const staticMapping = {
      'jannis/test': 'QmA...',
      'ensdomains/ens': 'QmB...',
    }

    return await Promise.all(
      names.map(async name => staticMapping[name])
    )
  },
})
```

### `@graphprotocol/query-engine-apollo`

This package provides an Apollo link for the above `QueryEngine`. It can be used as follows:

```typescript
import { createQueryEngine } from '@graphprotocol/query-engine'
import { createQueryEngineLink } from '@graphprotocol/query-engine-apollo'

let client = new ApolloClient({
  link: createQueryEngineLink({
    engine: createQueryEngine({ ... })
  })
})
```

## Proposed Documentation Updates

Each of the Query Engine packages comes with its own documentation.

* The documentation uses mdBook (like our specs)
* For each package there is a user guide
* Each abstract type / interface comes with API docs.
* Each exported implementation type comes with a user guide and API docs.

## Proposed Tests / Acceptance Criteria

* All component implementations come with unit tests written using Jest.
* The `@graphprotocol/query-engine` package comes with integration tests that run against mock index nodes and contracts deployed to Ganache.

## Tasks

- [x] (0.5d) Finalize plan for V0
- [x] (0.5d) Create documentation skeleton
- [x] (0.5d) Prepare repo for unit tests

### Query Engine

- [x] (1d) Add type definitions and interfaces to the query engine
  - Includes a rudimentary query plan based on GraphQL
- [x] (0.5d) Implement mock components for all parts of the query engine
- [x] (0.5d) Implement basic query engine
- [ ] (1d) Set up integration test environment using Ganache and The Graph contracts
- [x] (1d) Implement subgraph name resolution and node discovery using contracts
- [ ] (1d) Add documentation
  - Document all public types and interfaces
  - Document mock components in a testing section
  - Document query engine itself
  - Write user guide

### Apollo Link

- [x] (0.5d) Set up documentation
- [x] (0.5d) Implement the Apollo link based on the query engine
- [ ] (0.5d) Add documentation

**Comment by leodasvacas** [comment]
We'd discussed how it might make more sense to have each query engine correspond to a single subgraph rather than multiple subgraphs. This would avoid having to stitch schemas or anything like that. What are your current thoughts on this?

**Comment by Jannis** [comment]
@leodasvacas I wish we'd taken notes — do you remember what spoke for (and maybe against) a single subgraph?

**Comment by Jannis** [comment]
We can certainly start with that. Subgraph composition will allow to combine multiple subgraphs eventually, with one of them being the entry point. And if we detect the need to combine subgraphs through ways other than Apollo Federation / regular schema stitching / multiple Apollo links, we can still do that.

**Comment by leodasvacas** [comment]
@Jannis Sounds good. The argument is that a subgraph should behave like a self-contained API. Applications can combine multiple self-contained APIs, even by combining their graphql schemas, but I don't see why that should be a concern for the query engine.

**Comment by Jannis** [comment]
@leodasvacas If more than one subgraph are being used in a dApp/client, the more of these are known to the query engine, the better (cheaper, faster) decisions the query engine can make when routing these queries.

Let's say two subgraph APIs are stitched together with type `A` belonging to one subgraph and type `B` belonging to another. A query `as (...) { ... } bs (...) { ... }` would be split up into `as` and `bs` and sent separately, maybe to the same index node, maybe to different ones. But it'll be two roundtrips (at least).

If the query engine knows both subgraphs, it can send them both to the same index node and therefor save roundtrips and make things faster. This becomes more significant the more subgraphs are involved in the dApp/client.

**Comment by leodasvacas** [comment]
@Jannis that's a good argument for the query engine having knowledge of all subgraphs that are in use by an app. Though I'm not sold on that implying schema stitching done by the query engine, I'm concerned about name conflicts, which would be avoided by separate objects with separate schemas. Not sure what a solution that separates the objects but has some shared list of subgraphs would look like.

**Comment by Jannis** [comment]
@leodasvacas Right now people often merge schemas after one or more of them have been transformed with [transformSchema](https://www.apollographql.com/docs/apollo-server/features/schema-transforms/#transformschema). That could be one approach. But I agree, let's start simple, with one subgraph as the entry point.

**Comment by Jannis** [comment]
Documentation is now tracked in https://github.com/orgs/graphprotocol/projects/3#card-26497859.
